#!/usr/bin/bash

echo "Bios Vendor: "$(sudo dmidecode -s bios-vendor)
echo "Bios Version: "$(sudo dmidecode -s bios-version)
echo "Bios Release Date: "$(sudo dmidecode -s bios-release-date)
echo "System Manufacturer: "$(sudo dmidecode -s system-manufacturer)
echo "System Product Name: "$(sudo dmidecode -s system-product-name)
echo "System Version: "$(sudo dmidecode -s system-version)
echo "System Seriall Number: "$(sudo dmidecode -s system-serial-number)
echo "System UUID: "$(sudo dmidecode -s system-uuid)
echo "System Family: "$(sudo dmidecode -s system-family)
echo "Motherboard Manufacturer: "$(sudo dmidecode -s baseboard-manufacturer)
echo "Motherboard Product Name: "$(sudo dmidecode -s baseboard-product-name)
echo "Motherboard Version: "$(sudo dmidecode -s baseboard-version)
echo "Motherboard Serial Number: "$(sudo dmidecode -s baseboard-serial-number)
echo "Motherboard Asset Tag: "$(sudo dmidecode -s baseboard-asset-tag)
echo "Chassis Manufacturer: "$(sudo dmidecode -s chassis-manufacturer)
echo "Chassis Type: "$(sudo dmidecode -s chassis-type)
echo "Chassis Version: "$(sudo dmidecode -s chassis-version)
echo "Chassis Serial Number: "$(sudo dmidecode -s chassis-serial-number)
echo "Chassis Asset Tag: "$(sudo dmidecode -s chassis-asset-tag)
echo "Processor Family: "$(sudo dmidecode -s processor-family)
echo "Processor Manufacturer: "$(sudo dmidecode -s processor-manufacturer)
echo "Processor Version: "$(sudo dmidecode -s processor-version)
echo "Processor Frequency: "$(sudo dmidecode -s processor-frequency)
echo "Graphics Processor Family: "$(lspci | grep VGA | cut -d " " -f10)
echo "Graphics Processor Manufacturer: "$(lspci | grep VGA | cut -d " " -f5-8)
echo "Graphics Processor Version: "$(lspci | grep VGA | cut -d " " -f12-15)
echo "Total Installed RAM:" $(free -m  | awk '/^Mem:/{print $2}' | sed -re 's/([0-9])([0-9]{3})($|[^0-9])/\1,\2\3/')"MB"
